---
title: "FRST 556: Land Information Acquisition and Analysis"
author: "Chris Mulverhill (Professor)\nSarah Smith-Tripp (Teaching Assistant)"
date: "2024-07-31"  # You can use a fixed date or keep it dynamic with `date: "`r Sys.Date()`"`
description: "Open Educational Resources for FRST 556 course at the University of British Columbia"
format:
  html:
    toc: true
    number-sections: true
    link-citations: true
  pdf:
    toc: true
    number-sections: true
    biblio-style: apalike
    link-citations: true
documentclass: book
#bibliography: book.bib  # Ensure this points to your bibliography file
always_allow_html: true
---

# Welcome {.unnumbered}

These are the course materials for FRST 556 - Land Information Acquisition and Analysis. A course taught as part of the Masters in Forest Resources Management (MSFM) in the Faculty of Forestry at UBC. This course covers critical elements for accreditation by the Association of British Columbia Forest Professionals (ABCFP) and by the Society of American Foresters (SAF). The **9 exercises** of this course cover key knowledge concepts including:

-   Basic Level GIS

-   Plot and Stand Level Statistics

-   Working with Forest Inventory

-   Projecting forest inventory using TIPSY and VDYP

-   Developing management plans

This web-page hosts lab assignments that students enrolled in FRST 556 must complete for credit. **Note that much of the data referenced are either public datasets or otherwise only available to students enrolled in the course for credit**. Deliverables for these assignments are submitted through the UBC learning management system and only students enrolled in the course may submit these assignments for credit.

## How to use these resources {.unnumbered}

Each "module" is a standalone lab exercise designed to be completed over one or two weeks.

Students enrolled in FRST 556 will submit all deliverables through via the UBC course management system (canvas). Deadlines and submission locations can be found on canvas. The casual user can still complete the tutorials step-by-step, but not all data are publicly available nor are hosted on this website. Therefore a casual user may have issues completing all modules.

Unless otherwise noted, all materials are Open Educational Resources (OER) and licensed under a Creative Commons license (CC-BY-SA-4.0). Feel free to share and adapt, just be sure to share with the same license and give credit to the author.

## How to get involved {.unnumbered}

Because this is an open project, we highly encourage contributions from the community. The content is hosted on our [GitHub repository](https://github.com/ubc-geomatics-community-of-practice/FRST556-Land-Information-Acquisition-and-Analysis) and from there you can [open an issue or start a discussion](https://github.com/ubc-geomatics-community-of-practice/FRST556-Land-Information-Acquisition-and-Analysis/issues). Feel free to open an issue for any typos, factual discrepancies, bugs, or topics you want to see. We are always looking for great Canadian case studies to share! You can also fork our GitHub repository to explore the source code and take the content offline.